"""baseline

Revision ID: 0001
Revises: 
Create Date: 2026-10-06 09:07:13.521718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simulation_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('params', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('n_ticks', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flow_samples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('t', sa.Float(), nullable=False),
    sa.Column('src', sa.String(length=16), nullable=False),
    sa.Column('dst', sa.String(length=16), nullable=False),
    sa.Column('demand_gbps', sa.Float(), nullable=False),
    sa.Column('reachable', sa.Boolean(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('loss', sa.Float(), nullable=True),
    sa.Column('delivered_gbps', sa.Float(), nullable=False),
    sa.Column('hops', sa.Integer(), nullable=True),
    sa.Column('max_util', sa.Float(), nullable=True),
    sa.Column('distinct_paths', sa.Integer(), nullable=False),
    sa.Column('path', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['simulation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_flow_samples_run_t', 'flow_samples', ['run_id', 't'], unique=False)
    op.create_table('handoff_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('t', sa.Float(), nullable=False),
    sa.Column('station', sa.Integer(), nullable=False),
    sa.Column('from_sat', sa.Integer(), nullable=True),
    sa.Column('to_sat', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['simulation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_handoff_events_run_t', 'handoff_events', ['run_id', 't'], unique=False)
    op.create_table('link_samples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('t', sa.Float(), nullable=False),
    sa.Column('u', sa.String(length=16), nullable=False),
    sa.Column('v', sa.String(length=16), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=False),
    sa.Column('load_gbps', sa.Float(), nullable=False),
    sa.Column('capacity_gbps', sa.Float(), nullable=False),
    sa.Column('utilization', sa.Float(), nullable=False),
    sa.Column('queue_ms', sa.Float(), nullable=False),
    sa.Column('loss_eff', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['simulation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_link_samples_run_t', 'link_samples', ['run_id', 't'], unique=False)
    op.create_table('tick_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('t', sa.Float(), nullable=False),
    sa.Column('flows_total', sa.Integer(), nullable=False),
    sa.Column('flows_reachable', sa.Integer(), nullable=False),
    sa.Column('demand_gbps', sa.Float(), nullable=True),
    sa.Column('delivered_gbps', sa.Float(), nullable=True),
    sa.Column('delivery_ratio', sa.Float(), nullable=True),
    sa.Column('mean_latency_ms', sa.Float(), nullable=True),
    sa.Column('max_latency_ms', sa.Float(), nullable=True),
    sa.Column('loaded_links', sa.Integer(), nullable=False),
    sa.Column('max_link_util', sa.Float(), nullable=True),
    sa.Column('congested_links', sa.Integer(), nullable=False),
    sa.Column('overloaded_links', sa.Integer(), nullable=False),
    sa.Column('handoffs', sa.Integer(), nullable=False),
    sa.Column('outages', sa.Integer(), nullable=False),
    sa.Column('links_added', sa.Integer(), nullable=False),
    sa.Column('links_removed', sa.Integer(), nullable=False),
    sa.Column('route_changes', sa.Integer(), server_default='0', nullable=False),
    sa.Column('mean_hops', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['simulation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tick_metrics_run_t', 'tick_metrics', ['run_id', 't'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tick_metrics_run_t', table_name='tick_metrics')
    op.drop_table('tick_metrics')
    op.drop_index('ix_link_samples_run_t', table_name='link_samples')
    op.drop_table('link_samples')
    op.drop_index('ix_handoff_events_run_t', table_name='handoff_events')
    op.drop_table('handoff_events')
    op.drop_index('ix_flow_samples_run_t', table_name='flow_samples')
    op.drop_table('flow_samples')
    op.drop_table('simulation_runs')
    # ### end Alembic commands ###
